# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7628051f04a06cd2442cb567903583beade774cf273e70c1f221d2c6ef9344de94d74355465515c0d664b5f83805ca18bdbea5683f8f48440730fbe230fbbca

test:
  secret_key_base: 5736a78a48acec084e1a0e5ae8262c8cc7ac3500f6d021c8312a9d9efa8465e001d385dd0a19c496d391b122ff3454099291944322fe45e2de12e8982dc5f031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
